version: '3.4'
services:
  db:
    image: mysql:8.0.27
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 0510_admin_builders
      MYSQL_USER: admin_builders
      MYSQL_PASSWORD: 0510_admin_builders
      MYSQL_DATABASE: cliente-builders
    ports: 
      - "3308:3306"
    networks:
      - aasousa-network
  cadastro-cliente-api:
    image: aasousa/cadastro-cliente-api
    restart: always
    build: ./CadastroClienteAPIRest
    working_dir: /CadastroClienteAPIRest
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports: 
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - aasousa-network
networks:
    aasousa-network:
        driver: bridge